[general]
apikey="12345678901234567890123456789012"
lang="en"

[icons]
# day
"01d"= "â˜€ï¸"
"02d"= "â›…"
"03d"= "â˜ï¸"
"04d"= "â˜ï¸"
"09d"= "â˜”"
"10d"= "ğŸŒ§ï¸"
"11d"= "ğŸŒ©ï¸"
"13d"= "â„ï¸"
"50d"= "ğŸŒ«ï¸"
# night
"01n"= "ğŸŒ‘"
"02n"= "â˜ï¸"
"03n"= "â˜ï¸"
"04n"= "â˜ï¸"
"09n"= "â˜”"
"10n"= "ğŸŒ§ï¸"
"11n"= "ğŸŒ©ï¸"
"13n"= "â„ï¸"
"50n"= "ğŸŒ«ï¸"

[location]
# https://xkcd.com/2170/
lat=90.000
lon=90.000
